<a href="https://colab.research.google.com/github/jlee938/JEAwesome/blob/main/FinalP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import requests
import pandas as pd
import hashlib
from pathlib import Path
import gzip
import io

In [3]:
grocery_url = "https://data.cityofchicago.org/resource/3e26-zek2.csv"

params = {"$limit": 50000}

response = requests.get(grocery_url, params=params)

with open("grocery_data.csv", "wb") as f:
  f.write(response.content)

grocery_df = pd.read_csv('grocery_data.csv')

In [4]:
grocery_df

,store_name,address,zip,new_status,last_updated,location
0,Jewel - Osco,87 W 87th St,60620,OPEN,2020-06-03T17:00:00.000,POINT (-87.626243 41.736172)
1,Farm on Ogden,3555 W OGDEN AVE,60623,OPEN,2020-06-10T00:00:00.000,POINT (-87.71437 41.854608)
2,Jewel - Osco,5343 N Broadway St,60640-2311,OPEN,2020-06-03T17:00:00.000,POINT (-87.659887 41.978998)
3,International Foods NW,4404 W FULLERTON AVE,60639,OPEN,2020-06-10T00:00:00.000,POINT (-87.737127 41.924425)
4,Jewel - Osco,2520 N Narragansett Ave,60639-1041,OPEN,2020-06-03T17:00:00.000,POINT (-87.785559 41.926236)
...,...,...,...,...,...,...
259,Fat Lee Supermarket,2707 S WELLS ST,60616,OPEN,2020-06-10T00:00:00.000,POINT (-87.633033 41.843813)
260,Aldi,6220 N California Ave,60659-2608,OPEN,2020-06-04T15:00:00.000,POINT (-87.699541 41.994349)
261,Fair Share Finer Foods,6422 W 63rd Street,60638,OPEN,2020-06-04T15:00:00.000,POINT (-87.782075 41.777702)
262,Avenue Food Mart,6850 W BELMONT AVE,60634,OPEN,2020-06-10T00:00:00.000,POINT (-87.79769200000001 41.938134)
263,Lindo Michoacan,3142 W LAWRENCE AVE,60625,OPEN,2020-06-10T00:00:00.000,POINT (-87.707908 41.968473)

In [6]:

income_df = pd.read_csv('ChicagoZipMedian.csv')
income_df

,Label (Grouping),ZCTA5 60601!!Households!!Estimate,ZCTA5 60601!!Households!!Margin of Error,ZCTA5 60601!!Families!!Estimate,ZCTA5 60601!!Families!!Margin of Error,ZCTA5 60601!!Married-couple families!!Estimate,ZCTA5 60601!!Married-couple families!!Margin of Error,ZCTA5 60601!!Nonfamily households!!Estimate,ZCTA5 60601!!Nonfamily households!!Margin of Error,ZCTA5 60602!!Households!!Estimate,...,ZCTA5 60805!!Nonfamily households!!Estimate,ZCTA5 60805!!Nonfamily households!!Margin of Error,ZCTA5 60827!!Households!!Estimate,ZCTA5 60827!!Households!!Margin of Error,ZCTA5 60827!!Families!!Estimate,ZCTA5 60827!!Families!!Margin of Error,ZCTA5 60827!!Married-couple families!!Estimate,ZCTA5 60827!!Married-couple families!!Margin of Error,ZCTA5 60827!!Nonfamily households!!Estimate,ZCTA5 60827!!Nonfamily households!!Margin of Error
0,Total,"9,631",±777,"3,318",±659,"2,671",±603,"6,313",±836,712,...,"2,101",±330,"9,447",±631,"5,832",±418,"1,703",±285,"3,615",±533
1,"Less than $10,000",3.6%,±2.3,1.8%,±2.9,0.0%,±1.4,4.5%,±3.2,4.6%,...,8.5%,±6.3,21.4%,±3.5,19.3%,±4.9,9.0%,±5.7,25.0%,±6.2
2,"$10,000 to $14,999",0.2%,±0.4,0.0%,±1.1,0.0%,±1.4,0.3%,±0.5,2.7%,...,8.6%,±4.2,6.8%,±1.9,5.3%,±2.4,0.0%,±2.2,9.3%,±3.7
3,"$15,000 to $24,999",5.1%,±2.7,2.2%,±1.8,2.7%,±2.3,6.6%,±4.1,0.0%,...,8.8%,±4.4,8.8%,±2.6,7.3%,±2.5,0.5%,±0.7,13.1%,±4.7
4,"$25,000 to $34,999",5.0%,±4.5,2.5%,±4.1,3.1%,±5.0,6.3%,±6.6,5.5%,...,10.9%,±6.3,9.5%,±2.7,9.1%,±3.3,6.5%,±5.6,12.3%,±5.3
5,"$35,000 to $49,999",3.2%,±2.0,2.8%,±2.6,1.8%,±2.0,3.4%,±2.6,12.5%,...,10.8%,±4.7,15.0%,±2.9,16.9%,±4.3,16.5%,±6.0,12.3%,±5.0
6,"$50,000 to $74,999",6.5%,±3.0,1.4%,±2.4,0.0%,±1.4,9.2%,±4.1,9.4%,...,23.3%,±7.8,17.2%,±3.3,16.1%,±4.1,13.5%,±5.7,16.2%,±5.4
7,"$75,000 to $99,999",15.6%,±4.8,11.1%,±6.6,11.8%,±7.6,18.8%,±7.1,2.9%,...,21.0%,±7.6,7.6%,±2.3,9.1%,±2.9,15.9%,±6.9,5.2%,±4.0
8,"$100,000 to $149,999",25.2%,±6.8,15.0%,±7.5,13.2%,±8.1,30.5%,±9.2,20.9%,...,4.0%,±2.5,9.9%,±2.6,10.9%,±3.1,23.7%,±8.1,6.0%,±3.8
9,"$150,000 to $199,999",9.8%,±3.4,15.9%,±7.9,15.8%,±8.2,5.7%,±3.2,18.1%,...,2.2%,±2.0,2.4%,±1.3,3.8%,±2.1,9.9%,±5.8,0.0%,±1.0
10,"$200,000 or more",26.0%,±5.6,47.3%,±11.6,51.7%,±12.7,14.8%,±5.4,23.3%,...,2.0%,±2.1,1.5%,±0.9,2.1%,±1.3,4.5%,±3.2,0.5%,±0.8
11,Median income (dollars),"121,458","±10,903","188,864","±43,753","203,090","±53,736","102,404","±12,316","126,202",...,"53,551","±11,573","37,217","±4,075","42,953","±6,440","86,045","±17,288","28,456","±7,719"
12,Mean income (dollars),"209,944","±40,495","310,770","±79,240",N,N,"155,041","±42,512","159,169",...,"56,749","±7,757","51,168","±5,367","55,741","±4,924",N,N,"41,083","±10,922"
13,PERCENT ALLOCATED,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,Household income in the past 12 months,15.8%,(X),(X),(X),(X),(X),(X),(X),26.8%,...,(X),(X),57.6%,(X),(X),(X),(X),(X),(X),(X)
15,Family income in the past 12 months,(X),(X),10.7%,(X),(X),(X),(X),(X),(X),...,(X),(X),(X),(X),66.6%,(X),(X),(X),(X),(X)
16,Nonfamily income in the past 12 months,(X),(X),(X),(X),(X),(X),17.7%,(X),(X),...,49.3%,(X),(X),(X),(X),(X),(X),(X),43.2%,(X)

In [9]:
median_income_df = income_df[income_df['Label (Grouping)'] == 'Median income (dollars)']
median_income_df

,Label (Grouping),ZCTA5 60601!!Households!!Estimate,ZCTA5 60601!!Households!!Margin of Error,ZCTA5 60601!!Families!!Estimate,ZCTA5 60601!!Families!!Margin of Error,ZCTA5 60601!!Married-couple families!!Estimate,ZCTA5 60601!!Married-couple families!!Margin of Error,ZCTA5 60601!!Nonfamily households!!Estimate,ZCTA5 60601!!Nonfamily households!!Margin of Error,ZCTA5 60602!!Households!!Estimate,...,ZCTA5 60805!!Nonfamily households!!Estimate,ZCTA5 60805!!Nonfamily households!!Margin of Error,ZCTA5 60827!!Households!!Estimate,ZCTA5 60827!!Households!!Margin of Error,ZCTA5 60827!!Families!!Estimate,ZCTA5 60827!!Families!!Margin of Error,ZCTA5 60827!!Married-couple families!!Estimate,ZCTA5 60827!!Married-couple families!!Margin of Error,ZCTA5 60827!!Nonfamily households!!Estimate,ZCTA5 60827!!Nonfamily households!!Margin of Error
11,Median income (dollars),"121,458","±10,903","188,864","±43,753","203,090","±53,736","102,404","±12,316","126,202",...,"53,551","±11,573","37,217","±4,075","42,953","±6,440","86,045","±17,288","28,456","±7,719"

In [11]:
households_only_df = median_income_df[[col for col in median_income_df.columns if '!!Households!!' in col or col == 'Label (Grouping)']]

In [12]:
households_only_df

,Label (Grouping),ZCTA5 60601!!Households!!Estimate,ZCTA5 60601!!Households!!Margin of Error,ZCTA5 60602!!Households!!Estimate,ZCTA5 60602!!Households!!Margin of Error,ZCTA5 60603!!Households!!Estimate,ZCTA5 60603!!Households!!Margin of Error,ZCTA5 60604!!Households!!Estimate,ZCTA5 60604!!Households!!Margin of Error,ZCTA5 60605!!Households!!Estimate,...,ZCTA5 60707!!Households!!Estimate,ZCTA5 60707!!Households!!Margin of Error,ZCTA5 60803!!Households!!Estimate,ZCTA5 60803!!Households!!Margin of Error,ZCTA5 60804!!Households!!Estimate,ZCTA5 60804!!Households!!Margin of Error,ZCTA5 60805!!Households!!Estimate,ZCTA5 60805!!Households!!Margin of Error,ZCTA5 60827!!Households!!Estimate,ZCTA5 60827!!Households!!Margin of Error
11,Median income (dollars),"121,458","±10,903","126,202","±41,241","133,545","±39,960","81,658","±37,179","123,922",...,"84,799","±8,828","67,014","±11,117","70,842","±3,824","95,719","±9,207","37,217","±4,075"

In [13]:
final_households_df = households_only_df[[col for col in households_only_df.columns if 'Margin of Error' not in col]]

In [14]:
final_households_df

,Label (Grouping),ZCTA5 60601!!Households!!Estimate,ZCTA5 60602!!Households!!Estimate,ZCTA5 60603!!Households!!Estimate,ZCTA5 60604!!Households!!Estimate,ZCTA5 60605!!Households!!Estimate,ZCTA5 60606!!Households!!Estimate,ZCTA5 60607!!Households!!Estimate,ZCTA5 60608!!Households!!Estimate,ZCTA5 60609!!Households!!Estimate,...,ZCTA5 60657!!Households!!Estimate,ZCTA5 60659!!Households!!Estimate,ZCTA5 60660!!Households!!Estimate,ZCTA5 60661!!Households!!Estimate,ZCTA5 60706!!Households!!Estimate,ZCTA5 60707!!Households!!Estimate,ZCTA5 60803!!Households!!Estimate,ZCTA5 60804!!Households!!Estimate,ZCTA5 60805!!Households!!Estimate,ZCTA5 60827!!Households!!Estimate
11,Median income (dollars),"121,458","126,202","133,545","81,658","123,922","128,609","127,732","73,366","58,896",...,"110,939","68,704","67,479","125,741","84,530","84,799","67,014","70,842","95,719","37,217"

In [15]:
final_households_df.columns = [col.split()[-1].split('!!')[0] if 'ZCTA5' in col else col for col in final_households_df.columns]
final_households_df

,Label (Grouping),60601,60602,60603,60604,60605,60606,60607,60608,60609,...,60657,60659,60660,60661,60706,60707,60803,60804,60805,60827
11,Median income (dollars),"121,458","126,202","133,545","81,658","123,922","128,609","127,732","73,366","58,896",...,"110,939","68,704","67,479","125,741","84,530","84,799","67,014","70,842","95,719","37,217"

In [16]:
grocery_df['zip'] = grocery_df['zip'].astype(str).str[:5]
grocery_df['store_name'] = grocery_df['store_name'].str.upper()
grocery_df['address'] = grocery_df['address'].str.upper()
grocery_df = grocery_df.drop(columns = ['last_updated', 'location'])

In [17]:
grocery_df

                 store_name                  address    zip new_status
0              JEWEL - OSCO             87 W 87TH ST  60620       OPEN
1             FARM ON OGDEN         3555 W OGDEN AVE  60623       OPEN
2              JEWEL - OSCO       5343 N BROADWAY ST  60640       OPEN
3    INTERNATIONAL FOODS NW     4404 W FULLERTON AVE  60639       OPEN
4              JEWEL - OSCO  2520 N NARRAGANSETT AVE  60639       OPEN
..                      ...                      ...    ...        ...
259     FAT LEE SUPERMARKET          2707 S WELLS ST  60616       OPEN
260                    ALDI    6220 N CALIFORNIA AVE  60659       OPEN
261  FAIR SHARE FINER FOODS       6422 W 63RD STREET  60638       OPEN
262        AVENUE FOOD MART       6850 W BELMONT AVE  60634       OPEN
263         LINDO MICHOACAN     3142 W LAWRENCE  AVE  60625       OPEN

[264 rows x 4 columns]